### ISSUE TITLE
Rename repo to 'acs-override'

### ISSUE THREAD

**Issue by bramford** [raphendyr/avs-override#1]
The repository name `avs-override` seems to be misspelled given that the patches provide the `acs-override` feature as stated within the content of this repo.

**Comment by raphendyr** [comment]
Damnit. That is fairly good point... It appears I need to do some renaming :( Luckily, there probably aren't many users so far :D

**Comment by raphendyr** [comment]
Even my local folder was named correctly. Apparently I made mistake in my brain when creating the public repo and afterwards my corrective reading didn't notice it :D

Any case, renamed the repo, so remember to fix remote address on local configs.
